apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: secure-tasks

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: secure-tasks

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-sa
  namespace: secure-tasks

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: secure-tasks