apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: secure-tasks-backend
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend

  namespaceSelector:
    matchNames:
      - secure-tasks

  endpoints:
    - port: http
      path: /metrics
      interval: 15s